---
title: "Steam Sales Project"
output: html_notebook
author: Andrew Dai
date: 11.10.20
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(
ggplot2,
pwr,
ordinal,
lme4
)
```

```{r}

steam <- read.csv("steam.csv")

cat("Steam dataset has",as.character(nrow(steam)),"rows and",as.character(ncol(steam)),"columns:","\n")
cat(names(steam), sep=", ")

# Data Cleaning

# lower bound of owners range taken for each value
steam$owners <- as.integer(gsub("([0-9]+).*$", "\\1", steam$owners))
steam$release_year <- as.integer(gsub("([0-9]+).*$", "\\1", steam$release_date))
steam$total_ratings <- steam$positive_ratings+steam$negative_ratings

steam$genres <- strsplit(steam$genres, ";")
number_of_genre_tags <- sapply(steam$genres,function(x) length(x))
steam <- steam[which(number_of_genre_tags==1),]
steam$genres <- unlist(steam$genres)
genre_tags <- c("Action", "Indie", "Strategy", "RPG", "Racing", "Casual", "Adventure", "Sports", "Simulation", "Free to Play")

steam <- steam[sort(unlist(sapply(1:10,function(x) which(steam$genres==genre_tags[x])))),]
rownames(steam) <- 1:nrow(steam)

# keeping only games with 1 genre tag for simplicity's sake
# because games with multiple genre tags may be overlapping in groups
# keeping only 10 genres of games: Action, Indie, Strategy, RPG, Racing, Casual, Adventure, Sports, Simulation and Free to Play
# there is one game: "ADR Labellling game" that is skewing our price, I will remove it because it's inclusion is not valuable to our analysis

plot(steam$price,jitter(log(steam$owners),2),xlim=c(0,80), main="Effect of price on log(owners)")
plot(jitter(steam$release_year,2),jitter(log(steam$owners),2), main="Effect of release year on log(owners)")
plot(log(steam$total_ratings),jitter(log(steam$owners),2), main="Effect of total ratings on log(owners)", ylab="log(owners)", xlab="")

```

```{r}
# EDA
# Question: What makes a game popular on Steam?
# Definition of popular: many regular players

# Hypothesis / Variable Selection
# Price could be a variable that makes a game popular because if price is lower or free, it allows more people to afford the game.
# Positive ratings could be a variable that makes a game popular because it advertises the game to new players.
# Modern games should have a greater ownership than games created when Steam was first launched. However, games that have
# been just released may see a lag time before they are able to reach stable levels of ownership.

# log(owners) ~ beta0 + beta1(price) + beta2(positive_ratings/(positive_ratings+negative_ratings)) + beta3(release_year)

#

steam20 <- data.frame(owners=steam$owners, price=steam$price, ratings=steam$positive_ratings/(steam$positive_ratings+steam$negative_ratings), release_year=steam$release_year, genre=steam$genres)
steam20$owners <- factor(steam20$owners)

```

```{r}
ggplot(steam20, aes(y = ratings, x = price)) + geom_point() + geom_jitter() + 
  geom_smooth(method=lm) + xlim(0,60)

ggplot(steam20, aes(y = ratings, x = price, color = factor(genre))) + geom_point() + geom_jitter() + 
  geom_smooth(method=lm,alpha=0.2) + xlim(0,60)


```

```{r}

# multilevel model or causal inference

# poisson regression
model <- polr(owners~price+ratings+release_year+(1|factor(genre)),data=steam20)

```

```{r}
# Poisson
plot(predict(model),resid(model), main="Poisson Predicted vs Resids")

rootogram(steam20$owners, predict(model), scale = "raw")

# Negative Binomial 
plot(predict(model.nb),resid(model.nb), main="Poisson Predicted vs Resids")

rootogram(steam20$owners, predict(model.nb), scale = "raw")

# Zero Inflated
plot(predict(model.zi),resid(model.zi), main="Poisson Predicted vs Resids")

rootogram(steam20$owners, predict(model.zi), scale = "raw")

```

```{r}

steam20$genre <- factor(steam20$genre,labels=1:10)
#multilevel model
model.nb <- glm.nb(owners~price+ratings+release_year+(1|genre),data=steam20)

```


